# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa76268cd559a478ee5cc79691ac455c3e6613984b39c69f7e93aaf3fe0a50ff2a481a1a09ec464be041338e126b0adeb0137a4c35cdbfa9eaf6d8c3c881d79

test:
  secret_key_base: 901732639893848087e8b5268a78bf070ee6c4709f2993e5e163602e9c088a531eec890ec92b8ebb6112519a22362743d699fef15955a1ea7718fd1a6b2dc179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
